### ISSUE TITLE
Make the "Job Code" filter in the "cron jobs logs" page multi-select with predefined options

### ISSUE THREAD

**Issue by kanevbg** [mageplaza/magento-2-cron-schedule#11]
### Description (*)
Make the "Job Code" filter in the "cron jobs logs" page multi-select with predefined options.

### Expected behavior (*)
You can search and select jobs to filter from a predefined options, which are the ones existing in the system (registered job codes and unified with these existing in the cron_schedule table).

### Benefits
Ease of use, reduce time to operate with the logs, likely less people to be involved during searching for a cron job.

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza.
We will update this feature in the next version.
Please wait until it is released. 
Once again, thank you for your contribution

**Comment by giaphn** [comment]
Closed due to no response within 7 days
