### ISSUE TITLE
"Schedule now" action for cron jobs

### ISSUE THREAD

**Issue by kanevbg** [mageplaza/magento-2-cron-schedule#12]
### Description (*)
Gives the ability to schedule any task immediately and the cron observer to process it natively.

### Expected behavior (*)
When you "schedule now" one or more tasks trough the actions from the "Manage cron job" page, the selected tasks are scheduled in table cron_schedule which will make the cron observer to process the tasks on next execution.
![image](https://user-images.githubusercontent.com/11477130/112312875-f4d99e00-8caf-11eb-97a8-7c6d07c40530.png)
The screen shoot is from module Ethan3600/magento2-CronjobManager

### Benefits
You can schedule for execution now a given task(s) if they had been missed for any reason or when you setup new task which you need to run once now.

**Comment by giaphn** [comment]
Hi,
Thank you for taking the time here to talk about the ... module.
I've passed that feedback along to our development team to consider and review. 
Once again, I am deeply grateful for your valuable feedback and significant contribution.

**Comment by giaphn** [comment]
Closed due to no response within 7 days

**Comment by kanevbg** [comment]
?
