### ISSUE TITLE
System default configuration restore for cron tasks

### ISSUE THREAD

**Issue by kanevbg** [mageplaza/magento-2-cron-schedule#13]
### Description (*)
System default configuration restore
Revert back to the system's default configuration
![image](https://user-images.githubusercontent.com/11477130/112313154-39653980-8cb0-11eb-8d9a-89c06ea14e52.png)
Screen shoot is from module Ethan3600/magento2-CronjobManager

### Expected behavior (*)
This new action will revert back the cron task configuration to the original one.

### Benefits
Enhances the management by providing this new control which will be in use very likely for every big project and these migrating from Magento 1.

**Comment by giaphn** [comment]
Hi,
Thank you for taking the time here to talk about the ... module.
I've passed that feedback along to our development team to consider and review. 
Once again, I am deeply grateful for your valuable feedback and significant contribution.

**Comment by giaphn** [comment]
Closed due to no response within 7 days

**Comment by kanevbg** [comment]
?
