### ISSUE TITLE
[BUG] PHP 8.1

### ISSUE THREAD

**Issue by elisei** [mageplaza/magento-2-cron-schedule#17]
Exception: Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in vendor/mageplaza/module-cron-schedule/Helper/Email.php on line 92

### Preconditions (*)
1. Magento 2.4.5
2. PHP 8.1

### Steps to reproduce (*)
1. see the log

**Comment by jornwildenbeest** [comment]
I believe https://github.com/mageplaza/magento-2-cron-schedule/blob/2.4/Controller/Adminhtml/Job/Validate.php#L68 this line also casuses an error:

```
[2022-12-05T13:58:40.704058+00:00] main.ERROR: Deprecated Functionality: preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in /vendor/mageplaza/module-cron-schedule/Controller/Adminhtml/Job/Validate.php on line 68 [] []
```

This can be fixed this way:
```
$e        = count(preg_split('#\s+#', $schedule,  -1, PREG_SPLIT_NO_EMPTY));
```

**Comment by alitopaloglu** [comment]
This seems fixed and merged on [this](https://github.com/mageplaza/magento-2-cron-schedule/pull/18) PR

**Comment by KhietNguyen83** [comment]
Thank you for your interest in the Mageplaza extension.
I merge your issue, please check again.
Thanks a lot!

**Comment by jornwildenbeest** [comment]
@KhietNguyen83 Could you create a new release for these fixes?

**Comment by jornwildenbeest** [comment]
or @haitv282
