### ISSUE TITLE
mpcronschedule_send_email cron - Deprecated Functionality: explode()

### ISSUE THREAD

**Issue by DomPixie** [mageplaza/magento-2-cron-schedule#20]
php 8.1
Mage 2.4.5

Is possible to generate this error on cron

mpcronschedule_send_email

vendor/mageplaza/module-cron-schedule/Helper/Email.php on line 92

Deprecated Functionality: explode(): Passing null to parameter #2 ($string) of type string is deprecated in ./vendor/mageplaza/module-cron-schedule/Helper/Email.php on line 92

**Comment by KhietNguyen83** [comment]
Hi @DomPixie ,
Thank you for your interest in the Mageplaza extension.
Please help me to download the attachment and replace the Helper/Email.php file.
https://github.com/mageplaza/magento-2-cron-schedule/blob/2.4-develop/Helper/Email.php
Thank you!
