### ISSUE TITLE
Not registered handle mpcronschedule_log_grid_data_source

### ISSUE THREAD

**Issue by mtjweb** [mageplaza/magento-2-cron-schedule#4]
I installed the module on Magento 2.3.5-p1.

When I want to open System => Cron Schedule => Cron Jobs Logs, I'm getting the error "Not registered handle mpcronschedule_log_grid_data_source".

**Comment by mack4hack** [comment]
getting same issue on Magento 2.3.3

**Comment by geethq** [comment]
moving the following handle from etc/adminhtml/di.xml to etc/di.xml fixed the issue for me on 2.3.6

    <type name="Magento\Ui\Model\Export\MetadataProvider">
        <arguments>
            <argument name="data" xsi:type="array">
                <item name="mpcronschedule_log_grid" xsi:type="array">
                    <item name="created_at" xsi:type="string">created_at</item>
                    <item name="scheduled_at" xsi:type="string">scheduled_at</item>
                    <item name="executed_at" xsi:type="string">executed_at</item>
                    <item name="finished_at" xsi:type="string">finished_at</item>
                </item>
            </argument>
        </arguments>
    </type>

more reading,
https://magento.stackexchange.com/questions/156826/magento-2-issue-with-not-registered-handle-on-all-the-sales-sections

**Comment by stkrelax** [comment]
2.4.2-p1 same same
