### ISSUE TITLE
Kill long running processes

### ISSUE THREAD

**Issue by dbashyal** [mageplaza/magento-2-cron-schedule#5]
Sorry to ask a question on the issue section. 
I am looking into using this extension. Does this extension have a option to kill cron jobs after certain time? We have few jobs running for 10hrs and we want to kill it if it doesn't finish in max 2hrs.

Thank you.

**Comment by Shinichi69** [comment]
Hi @dbashyal 

Firstly, I truly apologize for the inconvenience.
Unfortunately, the current version has not supported this function yet. I'm so sorry about that. 
However, I will surely note it to our developer to consider developing it in the future. 

Thank you very much for your feedback.

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
