### ISSUE TITLE
Is it full compatible with Magento 2.4.1 ?

### ISSUE THREAD

**Issue by angelflo** [mageplaza/magento-2-cron-schedule#8]
Hello,

I would like to know if you cron scheduler has been tested and is full compatible with last version of Magento : 2.4.1 ?

Thanks a lot

**Comment by Shinichi69** [comment]
Hi @angelflo 

I’m Shin from Mageplaza and I will support you on this issue.

We tested with Magento 2.4.1 and found that the extension works well on this Magento version.
You can use the extension and if you have any problems with the extension, please contact us.

Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
