### ISSUE TITLE
Notice: Undefined index: id in ../Element/Iterator.php

### ISSUE THREAD

**Issue by webrod** [mageplaza/magento-2-cron-schedule#9]
### Preconditions (*)
2.4.2
### Steps to reproduce (*)

1. install via composer.phar require mageplaza/module-cron-schedule
2. bin/magento cache:clean
3. bin/magento cache:flush
4. sudo rm -r /home/bitnami/apps/magento/htdocs/generated/code/*
5. logout/login to admin
6. go to system->cron schedule->configuration

### Expected result (*)

1. should see the config page

### Actual result (*)
get an error message, cannot access the page, and cannot access any other configuration page anymore (but I can access the individual page of the module, only config break the site):
1 exception(s):
`Exception #0 (Exception): Notice: Undefined index: id in /opt/bitnami/apps/magento/htdocs/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63
Exception #0 (Exception): Notice: Undefined index: id in /opt/bitnami/apps/magento/htdocs/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63
<pre>#1 Magento\Config\Model\Config\Structure\Element\Iterator->setElements() called at [vendor/magento/module-config/Model/Config/Structure.php:146]
#2 Magento\Config\Model\Config\Structure->getTabs() called at [generated/code/Magento/Config/Model/Config/Structure/Interceptor.php:23]
#3 Magento\Config\Model\Config\Structure\Interceptor->getTabs() called at [vendor/magento/module-config/Block/System/Config/Tabs.php:77]
#4 Magento\Config\Block\System\Config\Tabs->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#5 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:66]
#6 Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#7 Magento\Framework\ObjectManager\ObjectManager->create() called at [vendor/magento/framework/View/Element/BlockFactory.php:46]
#8 Magento\Framework\View\Element\BlockFactory->createBlock() called at [vendor/magento/framework/View/Layout/Generator/Block.php:272]
#9 Magento\Framework\View\Layout\Generator\Block->getBlockInstance() called at [vendor/magento/framework/View/Layout/Generator/Block.php:252]
#10 Magento\Framework\View\Layout\Generator\Block->createBlock() called at [vendor/magento/framework/View/Layout/Generator/Block.php:229]
#11 Magento\Framework\View\Layout\Generator\Block->generateBlock() called at [vendor/magento/framework/View/Layout/Generator/Block.php:134]
#12 Magento\Framework\View\Layout\Generator\Block->process() called at [vendor/magento/framework/View/Layout/GeneratorPool.php:93]
#13 Magento\Framework\View\Layout\GeneratorPool->process() called at [vendor/magento/framework/View/Layout.php:365]
#14 Magento\Framework\View\Layout->generateElements() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:68]
#15 Magento\Framework\View\Layout\Interceptor->generateElements() called at [vendor/magento/framework/View/Layout/Builder.php:129]
#16 Magento\Framework\View\Layout\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Page/Builder.php:65]
#17 Magento\Framework\View\Page\Builder->generateLayoutBlocks() called at [vendor/magento/framework/View/Layout/Builder.php:65]
#18 Magento\Framework\View\Layout\Builder->build() called at [vendor/magento/framework/View/Layout.php:271]
#19 Magento\Framework\View\Layout->build() called at [vendor/magento/framework/View/Layout.php:896]
#20 Magento\Framework\View\Layout->getBlock() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:293]
#21 Magento\Framework\View\Layout\Interceptor->getBlock() called at [vendor/magento/module-backend/Model/View/Result/Page.php:26]
#22 Magento\Backend\Model\View\Result\Page->setActiveMenu() called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:23]
#23 Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu() called at [vendor/magento/module-config/Controller/Adminhtml/System/Config/Edit.php:57]
#24 Magento\Config\Controller\Adminhtml\System\Config\Edit->execute() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#25 Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#26 Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php:51]
#27 Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#28 Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#29 Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callPlugins() called at [generated/code/Magento/Config/Controller/Adminhtml/System/Config/Edit/Interceptor.php:23]
#30 Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->execute() called at [vendor/magento/framework/App/Action/Action.php:111]
#31 Magento\Framework\App\Action\Action->dispatch() called at [vendor/magento/module-backend/App/AbstractAction.php:151]
#32 Magento\Backend\App\AbstractAction->dispatch() called at [vendor/magento/module-config/Controller/Adminhtml/System/AbstractConfig.php:69]
#33 Magento\Config\Controller\Adminhtml\System\AbstractConfig->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#34 Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#35 Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/module-backend/App/Action/Plugin/Authentication.php:143]
#36 Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() called at [vendor/magento/framework/Interception/Interceptor.php:135]
#37 Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#38 Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->___callPlugins() called at [generated/code/Magento/Config/Controller/Adminhtml/System/Config/Edit/Interceptor.php:32]
#39 Magento\Config\Controller\Adminhtml\System\Config\Edit\Interceptor->dispatch() called at [vendor/magento/framework/App/FrontController.php:186]
#40 Magento\Framework\App\FrontController->processRequest() called at [vendor/magento/framework/App/FrontController.php:118]
#41 Magento\Framework\App\FrontController->dispatch() called at [vendor/magento/framework/Interception/Interceptor.php:58]
#42 Magento\Framework\App\FrontController\Interceptor->___callParent() called at [vendor/magento/framework/Interception/Interceptor.php:138]
#43 Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() called at [vendor/magento/framework/Interception/Interceptor.php:153]
#44 Magento\Framework\App\FrontController\Interceptor->___callPlugins() called at [generated/code/Magento/Framework/App/FrontController/Interceptor.php:23]
#45 Magento\Framework\App\FrontController\Interceptor->dispatch() called at [vendor/magento/framework/App/Http.php:116]
#46 Magento\Framework\App\Http->launch() called at [generated/code/Magento/Framework/App/Http/Interceptor.php:23]
#47 Magento\Framework\App\Http\Interceptor->launch() called at [vendor/magento/framework/App/Bootstrap.php:263]
#48 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:29]
</pre>`

**Comment by webrod** [comment]
I removed the 
<section id="mpcronschedule" ...
part of vendor/mageplaza/module-cron-schedule/etc/adminhtml/system.xml and now I can access the magento configuration page, but of course without the possibility to configure that module anymore

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza. 
Maybe this problem occurs because you haven't installed our Mageplaza_Core extension.
All our extension require module core to work.
Please help me re-check it.
Thank you very much!

**Comment by giaphn** [comment]
Closed due no response within 7 days.
